import os

AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_REGION = os.getenv('AWS_REGION')
AWS_PROFILE = os.getenv('AWS_PROFILE')

HTTP_ENDPOINT = os.getenv('HTTP_ENDPOINT')
SQS_QUEUE_URL = os.getenv('SQS_QUEUE_URL')
AUTH_BEARER_TOKEN = os.getenv('BEARER_TOKEN', None)

SQS_MAX_NUMBER_OF_MESSAGES = 10
